name: Merge Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm install -g pnpm@5.18.9
      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpmstore
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: pnpm install --store-dir=~/.pnpmstore
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm test
