name: Merge Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpmstore
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: volta-cli/action@v1
      - run: |
          npm install -g pnpm@5.18.9
          pnpm install --store-dir=~/.pnpmstore
          pnpm typecheck
          pnpm lint
          pnpm test
